"""rupgrading jobs tables

Revision ID: 2de761d13df8
Revises: 2f947a6f3804
Create Date: 2024-09-17 21:42:54.817068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de761d13df8'
down_revision: Union[str, None] = '2f947a6f3804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraping_jobs_results',
    sa.Column('number_of_jobs', sa.Integer(), nullable=True),
    sa.Column('exited_with_error', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('scraping_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraping_jobs',
    sa.Column('hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.drop_table('scraping_jobs_results')
    # ### end Alembic commands ###
